fix: Add CONTRIBUTING.md file
affinidi/vscode-extension pull request #61
Opened 2022-12-09 12:51 UTC by vitalyrudenko-affinidi

2022-12-09 13:29 UTC, lloydAffinidi submitted a review, later dismissed

2022-12-13 08:14 UTC, carlos-affinidi requested changes

2022-12-13 08:14 UTC, carlos-affinidi commented on CONTRIBUTING.md
> +We store all of our messages (errors, labels, etc.) in `src/messages/messages.ts` file.
```suggestion
We store all of our messages (errors, labels, etc.) in `src/messages/messages.ts` file. Additionally all of the user facing texts used in the `package.json` are stored in `package.nls.json`.
```

2022-12-13 08:14 UTC, carlos-affinidi commented on CONTRIBUTING.md
> +Configuration of the extension and CLI is stored in the `~/.affinidi/config.json` file.
```suggestion
Configurations of the extension and CLI are stored in the `~/.affinidi/config.json` file.  This file persists even after user log out.
```

2022-12-13 08:27 UTC, carlos-affinidi approved these changes

2022-12-13 08:27 UTC, merged

2022-12-13 09:48 UTC, ezgi-affinidi commented
:tada: This PR is included in version 1.6.1 :tada:

The release is available on:
- [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=Affinidi.affinidi)
- [GitHub release](https://github.com/affinidi/vscode-extension/releases/tag/v1.6.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: