feat(FTL-8509): add info about active and default project
affinidi/vscode-extension pull request #84
Opened 2023-01-10 13:58 UTC by anusha-kommu

2023-01-10 14:23 UTC, ezgi-affinidi submitted a review, later dismissed

2023-01-10 14:56 UTC, carlos-affinidi requested changes

2023-01-10 14:56 UTC, carlos-affinidi commented on README.md
> +Initially `Default project` will be your `Active Project`.
```suggestion
Initially the `Default Project` will be set as your `Active Project`.
```

2023-01-10 14:56 UTC, carlos-affinidi commented on README.md
> +Once the account is created, a `Default Project` will be created automatically. As part of it a digital identity will be created for you – your personal DID.
```suggestion
Once the account is created, a project named `Default Project` will be created automatically. As part of it, a digital identity will be created for you – your personal DID.
```

2023-01-10 14:56 UTC, carlos-affinidi commented on README.md
> +Active Project is the project on which you can perform all the [operations](#features) below. There will be only 1 active project at a time.
```suggestion
Your `Active Project` is the project on which you can perform all the [operations](#features) below. There will always be only 1 active project at a time.
```

2023-01-10 14:56 UTC, carlos-affinidi commented on README.md
> +You can also manually create projects by clicking on “Create project” button and enter a project’s name.
```suggestion
You can also manually create projects by clicking on `Create Project` button and enter a project’s name.
```

2023-01-10 14:56 UTC, carlos-affinidi commented on README.md
> +As the default project is the active project, all other projects will be shown under the `inactive projects` folder.
```suggestion
As the default project is the active project, all other projects will be shown under the `Inactive Projects` folder.
```

2023-01-11 12:57 UTC, anusha-kommu commented on README.md
> +As the default project is the active project, all other projects will be shown under the `inactive projects` folder.
done

2023-01-11 12:57 UTC, anusha-kommu commented on README.md
> +You can also manually create projects by clicking on “Create project” button and enter a project’s name.
done

2023-01-11 12:57 UTC, anusha-kommu commented on README.md
> +Active Project is the project on which you can perform all the [operations](#features) below. There will be only 1 active project at a time.
done

2023-01-11 12:57 UTC, anusha-kommu commented on README.md
> +Once the account is created, a `Default Project` will be created automatically. As part of it a digital identity will be created for you – your personal DID.
done

2023-01-11 14:27 UTC, vitalyrudenko-affinidi approved these changes

2023-01-11 14:27 UTC, vitalyrudenko-affinidi commented on README.md
> +![Activate Project](./media/docs/activate_project.png)
Personally, I think that **bold** here would make more sense than `monospace`, but this is nitpicking

2023-01-11 15:54 UTC, carlos-affinidi approved these changes

2023-01-12 10:11 UTC, merged

2023-01-17 06:05 UTC, ezgi-affinidi commented
:tada: This PR is included in version 1.10.0 :tada:

The release is available on:
- [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=Affinidi.affinidi)
- [GitHub release](https://github.com/affinidi/vscode-extension/releases/tag/v1.10.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: